name: labib
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.1.1
  firebase_auth: ^4.1.0
  cloud_firestore: ^4.0.3
  fluttertoast: ^8.0.9
  syncfusion_flutter_pdfviewer: ^20.2.46-beta
  open_mail_app: ^0.4.5
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.5
  camera: ^0.9.2+2
  tflite_flutter: ^0.9.0
  tflite_flutter_helper: ^0.2.1
  flutter_screenutil: ^5.0.0+2
  scidart: ^0.0.2-dev.6
  get_it: ^7.2.0
  equatable: ^2.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1    

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/words/
    - assets/HomePage/
    - assets/MainSectionPage/
    - assets/QuizSectionPage/
    - assets/grades/
    - assets/ress/
    - assets/pdfs/
    - assets/PlacementQuiz/
    - assets/letters/
    - assets/NumberTest/
    - assets/WordsGame/
    - assets/Account/
    - assets/welcomePage/
    - assets/models/keras_model.tflite
    - assets/models/
    - assets/ai/